name: ADF Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Node JS
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
        
        - name: validate node manager
          run: npm install
          working-directory: ${{ github.workspace}}/ADFRoot/build
        
        - name: Check Node js and Npm version
          run: |
            echo "Node Version:"
            node -v
            echo "Npm Version:"
            npm -v
            ls
          working-directory: ${{ github.workspace}}/ADFRoot/build
       

        - name: validate adf
          run: npm run build validate ${{ github.workspace }}/ADFRoot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID}}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.AZURE_DATA_FACTORY_NAME}}
          working-directory: ${{ github.workspace}}/ADFRoot/build