name: ADF Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Node JS
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
        
        - name: validate node manager
          run: npm install
          working-directory: ${{ github.workspace}}/ADFRoot/build
        
        - name: Check Node js and Npm version
          run: |
            echo "Node Version:"
            node -v
            echo "Npm Version:"
            npm -v
            ls
          working-directory: ${{ github.workspace}}/ADFRoot/build
        - name: check package.json
          run: |
            cat node_modules/@microsoft/azure-data-factory-utilities/lib/index.js
          working-directory: ${{ github.workspace}}/ADFRoot/build
       

        - name: validate adf
          run: npm run build validate ${{ github.workspace }}/ADFRoot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID}}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.AZURE_DATA_FACTORY_NAME}}
          working-directory: ${{ github.workspace}}/ADFRoot/build

        - name: genrate ARM Template
          run: npm run build export ${{ github.workspace }}/ADFRoot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID}}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.AZURE_DATA_FACTORY_NAME}} "Exported_ARM_Template"
          working-directory: ${{ github.workspace}}/ADFRoot/build

        - name: Upload ARM Template as artifact
          uses: actions/upload-artifact@v4
          with:
            name: arm-template
            path: ${{ github.workspace }}/ADFRoot/build/Exported_ARM_Template
    what-if-deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download ARM Template artifact
          uses: actions/download-artifact@v4
          with:
            name: arm-template
            path: ./arm-template
        - name: show downloaded files
          run: tree ./arm-template
        - name: display template file
          run: cat ./arm-template/ARMTemplateForFactory.json
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        

        
          
        