name: ADF Build and Genreate ARM Template
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: install node manager
        run: npm install

      - name: Check Node js and Npm version
        run: |
          echo "No Js version"
          node -v
          echo "Npm Version"
          npm -v

      - name: copy config file
        run: |
          mkdir -p ${{github.workspace}}/ADFRoot/build/config 
          cp ${{ github.workspace }}/ADFRoot/config/# ${{ github.workspace }}/ADFRoot/build/config/

      - name: validate adf
        run: npm run build validate ${{ github.workspace }}/ADFRoot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID}}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.AZURE_DATA_FACTORY_NAME}}
        working-directory: ${{ github.workspace}}/ADFRoot/build

      - name: genrate ARM Template
        run: npm run build export ${{ github.workspace }}/ADFRoot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID}}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.AZURE_DATA_FACTORY_NAME}} "Exported_ARM_Template"
        working-directory: ${{ github.workspace}}/ADFRoot/build

      - name: Upload ARM Template as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/ADFRoot/build
