name: ADF What If Deployment
on:
  workflow_call:
    secrets:
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: true
      AZURE_RESOURCE_GROUP:
        description: 'Azure Resource Group Name'
        required: true
      AZURE_CLIENT_ID:
        description: 'Azure Client ID'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID'
        required: true
jobs:
  whatif-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download ARM Template artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - name: show downloaded files
        run: tree ./build
      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
      - name: validate ARM Template
        run: |
          az deployment group validate \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP}} \
            --template-file ./build/Exported_ARM_Template/ARMTemplateForFactory.json \
            --parameters ./build/config/ARMTemplateParametersForFactory_dev.jsonc  \
            --mode incremental
      - name: what if ARM Template deployment
        run: |
            az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP}} \
            --template-file ./build/Exported_ARM_Template/ARMTemplateForFactory.json \
            --parameters ./build/config/ARMTemplateParametersForFactory_dev.jsonc \
            --mode incremental \
            --what-if